# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/**/*.(js|css)"
  [headers.values]
    Cache-Control = "public, max-age=604800"  # 1 week

[[headers]]
  for = "/assets/**/*.(jpg|jpeg|png|gif|webp|svg|ico)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"  # 1 month

[[headers]]
  for = "/sw-v2.js"
  [headers.values]
    Cache-Control = "no-store"