# Netlify configuration file

# Build settings
[build]
  command = "npm run build"  # Build command for Vite
  publish = "dist"           # Output directory for Vite

# Redirects for SPA routing
[[redirects]]
  from = "/*"                # Match all paths
  to = "/index.html?v=3"     # Serve index.html with cache-busting param
  status = 200               # Use 200 status (rewrite, not redirect)

# Headers for static assets and security
[[headers]]
  for = "/**/*.(jpg|jpeg|png|gif|webp|svg|ico)"  # Image files
  [headers.values]
    Cache-Control = "public, max-age=31536000"  # 1 year

[[headers]]
  for = "/*"  # All files
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' ws://localhost:5173;"  # CSP for security
    Cache-Control = "no-store"  # Force fresh fetch for HTML

[[headers]]
  for = "/sw-v3.js"  # Already updated to sw-v3.js
  [headers.values]
    Cache-Control = "no-store"  # No caching at all