export const pokeballs = [
    { name: "Poké Ball", multiplier: 1, apiName: "poke-ball" },
    { name: "Great Ball", multiplier: 1.5, apiName: "great-ball" },
    { name: "Ultra Ball", multiplier: 2, apiName: "ultra-ball" },
    { name: "Master Ball", multiplier: 255, apiName: "master-ball" },
    { name: "Safari Ball", multiplier: 1.5, apiName: "safari-ball" },
    { name: "Net Ball", multiplier: (pokemonType: string) => pokemonType === "Water" || pokemonType === "Bug" ? 3.5 : 1, apiName: "net-ball" },
    { name: "Nest Ball", multiplier: (level: number) => Math.max(1, Math.min(4, 7 - 0.2 * (level - 1))), apiName: "nest-ball" },
    { name: "Repeat Ball", multiplier: (caughtCount: number) => Math.min(2.5, 1 + 0.5 * caughtCount), apiName: "repeat-ball" },
    { name: "Timer Ball", multiplier: (turns: number) => Math.min(4, 1 + 0.3 * turns), apiName: "timer-ball" },
    { name: "Luxury Ball", multiplier: 1, apiName: "luxury-ball" },
    { name: "Premier Ball", multiplier: 1.5, apiName: "premier-ball" },
    { name: "Dive Ball", multiplier: (isWaterDwelling: boolean) => isWaterDwelling ? 3.5 : 1, apiName: "dive-ball" },
    { name: "Dusk Ball", multiplier: (isNight: boolean, isCave: boolean) => (isNight || isCave) ? 2.5 : 1, apiName: "dusk-ball" },
    { name: "Heal Ball", multiplier: 1.25, apiName: "heal-ball" },
    { name: "Quick Ball", multiplier: (isFirstTurn: boolean) => isFirstTurn ? 5 : 1, apiName: "quick-ball" },
    { name: "Cherish Ball", multiplier: 2, apiName: "cherish-ball" },
    { name: "Dream Ball", multiplier: (sleepTurns: number) => Math.min(4, 1 + 0.3 * sleepTurns), apiName: "dream-ball" },
    { name: "Fast Ball", multiplier: (speed: number) => Math.min(4, 1 + speed / 100), apiName: "fast-ball" },
    { name: "Friend Ball", multiplier: (isHappinessEvolution: boolean) => isHappinessEvolution ? 2.5 : 1, apiName: "friend-ball" },
    { name: "Heavy Ball", multiplier: (weight: number) => Math.min(4, 1 + weight / 100), apiName: "heavy-ball" },
    { name: "Level Ball", multiplier: (pokemonLevel: number, wildLevel: number) => pokemonLevel === wildLevel ? 4 : 1, apiName: "level-ball" },
    { name: "Love Ball", multiplier: (isOppositeGender: boolean, isSameEvolutionLine: boolean) => (isOppositeGender && isSameEvolutionLine) ? 8 : 1, apiName: "love-ball" },
    { name: "Lure Ball", multiplier: (isFishingRodCatch: boolean) => isFishingRodCatch ? 4 : 1, apiName: "lure-ball" },
    { name: "Moon Ball", multiplier: (isMoonStoneEvolution: boolean) => isMoonStoneEvolution ? 4 : 1, apiName: "moon-ball" },
  ];
  