export const pokeballs = [
    { name: "Poké Ball", multiplier: 1, apiName: "poke-ball", description: "1x" },
    { name: "Great Ball", multiplier: 1.5, apiName: "great-ball", description: "1.5x" },
    { name: "Ultra Ball", multiplier: 2, apiName: "ultra-ball", description: "2x" },
    { name: "Master Ball", multiplier: 255, apiName: "master-ball", description: "255x Guaranteed catch" },
    { name: "Safari Ball", multiplier: 1.5, apiName: "safari-ball", description: "1.5x" },
    { name: "Net Ball", multiplier: (pokemonType: string) => pokemonType === "Water" || pokemonType === "Bug" ? 3.5 : 1, apiName: "net-ball", description: "3.5x if used on a Water- or Bug-type Pokémon: 1x otherwise" },
    { name: "Nest Ball", multiplier: (level: number) => Math.max(1, Math.min(4, 7 - 0.2 * (level - 1))), apiName: "nest-ball", description: "(7 - (0.2 * (level - 1))x: 1x minimum, 4x maximum rate" },
    { name: "Repeat Ball", multiplier: (caughtCount: number) => Math.min(2.5, 1 + 0.5 * caughtCount), apiName: "repeat-ball", description: "Increases for each successive catch (0.1x) on a Pokémon up to 2.5x. Resets to 1x on a different Pokémon" },
    { name: "Timer Ball", multiplier: (turns: number) => Math.min(4, 1 + 0.3 * turns), apiName: "timer-ball", description: "(1 + (turn count * 0.30))x maximum 4x at 11 turns, minimum 1.0x on first turn" },
    { name: "Luxury Ball", multiplier: 1, apiName: "luxury-ball", description: "1x Doubles the rate in which the contained Pokémon receives friendship" },
    { name: "Premier Ball", multiplier: 1.5, apiName: "premier-ball", description: "1.5x" },
    { name: "Dive Ball", multiplier: (isWaterDwelling: boolean) => isWaterDwelling ? 3.5 : 1, apiName: "dive-ball", description: "3.5x if used on a water-dwelling Pokémon: 1x otherwise" },
    { name: "Dusk Ball", multiplier: (isNight: boolean, isCave: boolean) => (isNight || isCave) ? 2.5 : 1, apiName: "dusk-ball", description: "2.5x if used in a cave or at night: 1x otherwise" },
    { name: "Heal Ball", multiplier: 1.25, apiName: "heal-ball", description: "1.25x Fully restores a caught Pokémon's HP, PP, and status" },
    { name: "Quick Ball", multiplier: (isFirstTurn: boolean) => isFirstTurn ? 5 : 1, apiName: "quick-ball", description: "5x if used on the first turn of a battle: 1x otherwise" },
    { name: "Cherish Ball", multiplier: 2, apiName: "cherish-ball", description: "2x" },
    { name: "Dream Ball", multiplier: (sleepTurns: number) => Math.min(4, 1 + 0.3 * sleepTurns), apiName: "dream-ball", description: "Better catch rate if the Pokémon has been asleep for more turns, max catch rate of 4x, minimum catch rate of 1x" },
    { name: "Fast Ball", multiplier: (speed: number) => Math.min(4, 1 + speed / 100), apiName: "fast-ball", description: "Better catch rate if the Pokémon has a higher base Speed, max catch rate of 4x, minimum catch rate of 1x" },
    { name: "Friend Ball", multiplier: (isHappinessEvolution: boolean) => isHappinessEvolution ? 2.5 : 1, apiName: "friend-ball", description: "2.5x if used on Pokémon which evolve due to happiness: 1x otherwise" },
    { name: "Heavy Ball", multiplier: (weight: number) => Math.min(4, 1 + weight / 100), apiName: "heavy-ball", description: "Better catch rate if the Pokémon is heavier, max catch rate of 4x, minimum catch rate of 1x " },
    { name: "Level Ball", multiplier: (pokemonLevel: number, wildLevel: number) => pokemonLevel === wildLevel ? 4 : 1, apiName: "level-ball", description: "4x if used on Pokémon who are the same level as yours: 1x otherwise" },
    { name: "Love Ball", multiplier: (isOppositeGender: boolean, isSameEvolutionLine: boolean) => (isOppositeGender && isSameEvolutionLine) ? 8 : 1, apiName: "love-ball", description: "8x if used on Pokémon in the same evolution line as yours and the opposite gender: 1x on genderless foes and otherwise" },
    { name: "Lure Ball", multiplier: (isFishingRodCatch: boolean) => isFishingRodCatch ? 4 : 1, apiName: "lure-ball", description: "4x if used on a Pokémon hooked by a fishing rod: 1x otherwise" },
    { name: "Moon Ball", multiplier: (isMoonStoneEvolution: boolean) => isMoonStoneEvolution ? 4 : 1, apiName: "moon-ball", description: "4x if used on Pokémon that evolves using a Moon Stone: 1x otherwise" },
  ];
  